

name: CI

on: 
  push:
   
jobs:
  Yuvi-Terraform-deploy: 
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.13.1
